# Generated by Django 5.2.7 on 2025-11-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0003_remove_task_due_date_task_due_datetime_task_notified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='phone_number',
        ),
    ]
